name: blu_mat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Provider package
  provider: ^6.1.5+1

  # Pacakge to connect with BLE Devices (new)
  flutter_blue_plus: ^2.0.0

  # Package to Bluetooth Classic Devices (old)
  flutter_bluetooth_serial: ^0.4.0

  # for handling runtime permissions
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for linting
  flutter_lints: ^6.0.0

  # for App Icon
  # flutter_launcher_icons: ^0.14.4

# flutter Launcer Icons for changing the app icon 
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   adaptive_icon_foreground: "assets/icon/icon.png"
#   adaptive_icon_background: "#ffffff"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "assets/icon/icon.png"
#     background_color: "#ffffff"
#     theme_color: "#3F51B5"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/
